# Site settings
baseurl: "http://miqo.jekyll.sarhov.com/" # the subpath of your site, e.g. /blog/
url: "http://miqo.jekyll.sarhov.com/" # the base hostname & protocol for your site
highlighter: rouge
permalink: /:title/
# Build settings
markdown: kramdown
future: true
# collections:
#   homepage:
#     output: true
#     permalink: /:collection/:name
#   sidebar:
#     output: true
#     permalink: /:collection/:name