# Site settings
url: "http://miqo.jekyll.sarhov.com/" # the base hostname & protocol for your site
baseurl: ""
highlighter: rouge
permalink: /:title/
# Build settings
markdown: kramdown
future: true
# sass:
#     style: :compressed
# collections:
#   homepage:
#     output: true
#     permalink: /:collection/:name
#   sidebar:
#     output: true
#     permalink: /:collection/:name