### GLOBAL  ###
title: MiQo - Jekyll Theme
description: |
  Minimal & Clean Jekyll theme
#----------------------------------------

### homepage ###
homepage:
  - subscribe: true #true/false
    cover: 'subscribe_cover.png'
    mailchimp_url: ''


#------------------------------------


### SIDEBAR ###

#------------------------------------


### SINGLE POST PAGE  ###

#-------------------------------


### SINGLE POST PAGE  ###

#--------------------------------