### GLOBAL  ###
title: MiQo - Jekyll Theme
description: |
  Minimal & Clean Jekyll theme
#----------------------------------------

### homepage ###
homepage:
  subscribe: 
    cover: 'subscribe_cover.jpg'
    mailchimp_url: ''


#------------------------------------


### SIDEBAR ###

#------------------------------------


### SINGLE POST PAGE  ###

#-------------------------------


### SINGLE POST PAGE  ###

#--------------------------------