### GLOBAL  ###
title: MiQo - Jekyll Theme
description: |
  Minimal & Clean Jekyll theme

social:
  facebook: 'https://facebook.com'
  twitter:  'https://twitter.com'
  linkedin: ''
  instagram: 'https://instagram.com'
  google-plus: ''
  pinterest: ''
  youtube: ''
  github: 'https://github.com'
  email: 'sarhov@sarhov.com'
#----------------------------------------

### homepage ###
homepage:
  subscribe: 
    cover: 'subscribe_cover.jpg'
    mailchimp_url: ''


#------------------------------------


### SIDEBAR ###

#------------------------------------


### BlogPAGE  ###
blog:
  sidebar: 'true'
  posts_per_page: '24'
#-------------------------------


### SINGLE POST PAGE  ###

#--------------------------------